cosmic-panel-config/src/config.rs

It wasn't obvious that the error was about parsing the ron config without any context.

Output error message with more context when parsing configs

---

Cargo.lock

fixes the output hotplug issues

fix: update xdg-shell-wrapper for fix

---

Cargo.lock
cosmic-panel-bin/Cargo.toml
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/wrapper_space.rs

Border radius jammy

---

Cargo.lock
cosmic-panel-bin/Cargo.toml
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/wrapper_space.rs

Most of the fixes for cursor icons are in https://github.com/pop-os/xdg-shell-wrapper/commit/9ae1c4c838fe58e887b62d2a990d73ab2f6cb629

fix: cursor icons & update deps

---

Cargo.lock
Cargo.toml
cosmic-panel-bin/Cargo.toml
cosmic-panel-bin/src/config_watching.rs
cosmic-panel-bin/src/main.rs
cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/mod.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/popup.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/space/toplevel.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/mod.rs
cosmic-panel-bin/src/space_container/space_container.rs
cosmic-panel-bin/src/space_container/toplevel.rs
cosmic-panel-bin/src/space_container/wrapper_space.rs
cosmic-panel-config/Cargo.toml
flake.nix

This makes the panel expand, autohide, & disable transparency, border radius and gaps when there is a maximized window on the same output.

Maximized jammy

---

cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-config/src/panel_config.rs

This seems to fix the artifacts from the latest version, and also fixes so that the dock doesn't pop up immediately after its layer surface is created, whether or not it is given focus. It only pops up when it is hovered.

fix: improve layout of panel, improve rendering, and use hover state instead of focus state for visibility

---

Cargo.lock
cosmic-panel-bin/src/space_container/toplevel.rs

~~Draft until https://github.com/pop-os/cosmic-protocols/pull/20 is merged and branch names can be dropped from Cargo.toml.~~

deps: Update cosmic-protocols

---

Cargo.lock
Cargo.toml
cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-config/Cargo.toml
cosmic-panel-config/src/panel_config.rs

The initial draw of the panel background was always stretched, so I skip drawing the background the first draw now.

Panel improvements jammy

---

Cargo.lock
Cargo.toml
cosmic-panel-bin/Cargo.toml
cosmic-panel-bin/src/config_watching.rs
cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/space_container.rs
cosmic-panel-bin/src/space_container/toplevel.rs
cosmic-panel-bin/src/space_container/workspace.rs
cosmic-panel-bin/src/space_container/wrapper_space.rs
cosmic-panel-config/Cargo.toml
cosmic-panel-config/src/panel_config.rs

This seems to be working pretty well now with changes in cosmic-settings and maximized windows

Panel animation jammy

---

cosmic-panel-bin/src/space/panel_space.rs

fix autohide panic

---

cosmic-panel-bin/src/space_container/toplevel.rs

Not sure if this is 100% the right approach, but this fixes the panels background after unmaximizing a window for me as I am using a custom color value instead of a theme. Previously I had to restart the panel to get my color back.

Fix custom background color after maximize

---

cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/render.rs

eventually single pixel buffer should be used

fix: premultiply bg color and always use MemoryRenderBuffer

---

cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/mod.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/popup.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/mod.rs
cosmic-panel-bin/src/space_container/toplevel.rs

This PR allows the applets to set an integer priority for being an alternative minimize applet. The panel will also push an environment variable `X_MINIMIZE_APPLET` which evaluates to `true` if it is selected as a minimize applet, `false` otherwise

feat: modify panel applets to take minimize priority number instead of flag

---

cosmic-panel-bin/src/space_container/space_container.rs

fix: restart after anchor change

---

cosmic-panel-bin/src/space_container/wrapper_space.rs

fix: popup performance

---

cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space_container/space_container.rs

https://github.com/pop-os/cosmic-panel/assets/153014021/ac76ef4b-c5c7-400a-a915-701c2a571bad
https://github.com/pop-os/cosmic-panel/assets/153014021/784cbe87-e071-480f-8e9d-2ec48cb321ce

fix: don't animate autohide panel on maximize

---

Cargo.lock

fix: udpate xdg-shell-wrapper

---

cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space_container/space_container.rs
cosmic-panel-bin/src/space_container/toplevel.rs

fix: use color override when maximized

---

Cargo.lock
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/space_container.rs
cosmic-panel-bin/src/space_container/toplevel.rs
cosmic-panel-bin/src/space_container/wrapper_space.rs
cosmic-panel-config/src/panel_config.rs

should fix https://github.com/pop-os/cosmic-panel/issues/172

fix: stacked panels avoid each other

---

cosmic-panel-bin/src/space/render.rs

fixes https://github.com/pop-os/cosmic-applets/issues/535

fix: crop overflow elements

---

cosmic-panel-bin/src/space/popup.rs

fix: destroy wl_surface after popup cleanup

---

cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/data_device/data_device.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/data_device/data_source.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/mod.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/state.rs

fix: selection

---

cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/wrapper_space.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/data_device/data_device.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/pointer.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/state.rs
cosmic-panel-bin/src/xdg_shell_wrapper/mod.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/compositor.rs
cosmic-panel-bin/src/xdg_shell_wrapper/shared_state.rs
cosmic-panel-bin/src/xdg_shell_wrapper/space/space.rs

refactor: process generated pointer events immediately, replacing the actual event

---

Cargo.lock
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/pointer.rs

fix: update launchpad

---

cosmic-panel-bin/src/xdg_shell_wrapper/client/state.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/compositor.rs
cosmic-panel-bin/src/xdg_shell_wrapper/shared_state.rs

fix: layer shell surface scaling

---

cosmic-panel-bin/src/main.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space_container/space_container.rs

should fix some of the recent reported freezes like #292 and maybe #287

fix: use unbounded channel to avoid locking when it fills up

---

cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/xdg_shell.rs

Fix popup focus

---

cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/xdg_shell_wrapper/mod.rs

may fix #302, but I'm not able to recreate the issue.

sleep for up to 50ms if there is time left in the iteration timeout

---

cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/wrapper_space.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/data_device/data_device.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/pointer.rs
cosmic-panel-bin/src/xdg_shell_wrapper/space/space.rs
cosmic-panel-config/src/container_config.rs
cosmic-panel-config/src/panel_config.rs

should fix #190. @pop-os/ux does 500ms delay seem ok as a default, or should it be changed?

feat: delay for autohover popups

---

cosmic-panel-bin/src/space/overflow.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/state.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/compositor.rs
cosmic-panel-bin/src/xdg_shell_wrapper/space/popup.rs

fix: make context current with surface

---

cosmic-panel-bin/src/space/popup.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/xdg_shell_wrapper/space/popup.rs

This will reduce popup issues. There are a couple improvements that could be done for libcosmic as well.

Improv popup

---

cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/panel_space.rs

fix: apply new location after focus transition has ended

---

cosmic-panel-bin/src/space/wrapper_space.rs

fix: exit early if the hovered applet has a popup

---

cosmic-panel-bin/src/iced/elements/target.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/wrapper_space.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/mod.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/seat.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/touch.rs
cosmic-panel-bin/src/xdg_shell_wrapper/client/state.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/mod.rs
cosmic-panel-bin/src/xdg_shell_wrapper/space/space.rs

Updated from https://github.com/pop-os/cosmic-panel/pull/199 and https://github.com/pop-os/xdg-shell-wrapper/pull/22.
Probably better to merge some version of this and improve latter, instead of leaving it unmerged indefinitely.
But it seems to crash sometimes trying to change workspaces with this? Exiting with status code 101? I saw that with another cosmic-panel change, but not sure what's going on there (that's different from SIGABRT or other signals killing the process...)

Initial support for touch input, version 2

---

Cargo.lock
cosmic-panel-bin/Cargo.toml
cosmic-panel-bin/src/iced/elements/mod.rs
cosmic-panel-bin/src/iced/elements/target.rs
cosmic-panel-bin/src/iced/mod.rs
cosmic-panel-bin/src/space/layout.rs
cosmic-panel-bin/src/space/panel_space.rs
cosmic-panel-bin/src/space/render.rs
cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/space_container/space_container.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/mod.rs

Following up on https://github.com/pop-os/cosmic-panel/pull/422, I want to add support for touch input for the overflow button and popup, but without duplicating code too much.

Refactoring point/touch focus/target code; touch support for overflow

---

cosmic-panel-bin/src/space/wrapper_space.rs

fix: handle press in space if hovered

---

cosmic-panel-bin/src/space/wrapper_space.rs
cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/xdg_shell.rs

Should fix https://github.com/pop-os/cosmic-workspaces-epoch/issues/222.

fix: Close workspaces for popups that take grabs; not tooltips
