cosmic-panel-bin/src/space.rs
This PR updates the `Space::spawn_clients` function of cosmic-panel by ensuring, that no more than one process is spawned for a single desktop-file id / app_id, and cleans up some unnecessary allocations (as well as some beautiful but scary iterator-chains) in the process.
=> Avoid spawning an applet multiple times

cosmic-panel-bin/src/space/wrapper_space.rs
Popups previously were created with the same positioner and size, but not with the matching xdg_surface.window_geometry, leading to decorations such as drop-shadows to be treated as window contents, which caused slightly offset positioning.
This PR fixes that.
=> popups: Fix window geometry

config.ron, cosmic-panel-config/src/container_config.rs
CI is failing already on `master_jammy`. I'm not sure what issue it has with the `smithay-client-toolkit` dependency, since `Cargo.lock` only has it depending on one version, with a commit that should be fine...
=> Use `config.ron` as default with `include_str!`, add audio/status area applets

Cargo.lock, cosmic-panel-bin/Cargo.toml, cosmic-panel-bin/src/main.rs
This integrates a bit better than having `cosmic-session` copy logs from stderr to journald, and works when not started through `cosmic-session`.
Having panics logged should be helpful if panics ever occur.
=> Log to journald, and log panics

cosmic-panel-bin/src/space/panel_space.rs, cosmic-panel-bin/src/space/wrapper_space.rs
This should make the panel usable in sway, assuming config adjustments are made to not use applets relying on cosmic-protocols and keyboard interactivity is set to none.
=> fix: popup size & only reposition popups if supported

cosmic-panel-bin/src/space/layout.rs
leaving the actual size unconstrained can allow an applet that is too large to affect the centering of other applets
=> fix: actual size of list should be constrained

cosmic-panel-bin/src/space/layout.rs
=> fix(layout): only constrain the cross dimension of the actual size

cosmic-panel-bin/src/space/wrapper_space.rs
they need the same id so they can all be cleaned up together when the panel is dropped. should fix #111
=> fix: use panel id when starting new applet

data/default_schema/com.system76.CosmicPanel.Dock/v1/autohide
=> chore: disable dock autohide by default

cosmic-panel-bin/src/space/layout.rs, cosmic-panel-bin/src/space/panel_space.rs, cosmic-panel-bin/src/space/wrapper_space.rs, cosmic-panel-config/src/panel_config.rs
This also accounts for the active gap when constraining sizes. Should fix #138
=> fix: unmap applets whose size is too large, and map them again when possible

cosmic-panel-config/src/panel_config.rs
This PR fixes the behavior of autohide panels/docks when a maximized window is focused.
Previously, the panel/dock would expand itself to the edges, regardless of whether the setting is turned off in the settings. While this is appropriate for regular panels, autohide panels/docks should not expand to edges unless it's set that way in settings.
https://github.com/pop-os/cosmic-panel/assets/56272643/0d47bdaa-59ae-4c6f-8c6a-b8342fc2218e
=> fix: preserve non-maximized config for autohide panels/docks

cosmic-panel-bin/src/space/wrapper_space.rs
This can make it more useful for applets with lists of items. The press is still moved in four pixels if it is on the outer 4.
=> refactor: don't center generated pointer press

cosmic-panel-bin/src/space/layout.rs, cosmic-panel-bin/src/space/panel_space.rs, cosmic-panel-bin/src/space/wrapper_space.rs
=> fix: prevent unmapping windows when downscaling

Cargo.toml, cosmic-panel-bin/src/space_container/space_container.rs
ensure that priority comparisons are only applied to adjecent panels, and not self
=> fix: more refined config updates

Cargo.toml
If the project isn't GPL-3.0-only, let me know and I can modify the PR!
=> chore: add SPDX license identifier to Cargo workspace

cosmic-panel-bin/src/space_container/space_container.rs
Removes clippy error and prevents potential usize underflow scenarios.
=> fix: convert usize to isize

cosmic-panel-bin/src/iced/elements/background.rs, cosmic-panel-bin/src/iced/mod.rs, cosmic-panel-bin/src/main.rs, cosmic-panel-bin/src/minimize.rs, cosmic-panel-bin/src/space/layout.rs, cosmic-panel-bin/src/space/overflow.rs, cosmic-panel-bin/src/space/panel_space.rs, cosmic-panel-bin/src/space/popup.rs, cosmic-panel-bin/src/space/render.rs, cosmic-panel-bin/src/space/wrapper_space.rs, cosmic-panel-bin/src/space_container/space_container.rs, cosmic-panel-bin/src/space_container/toplevel.rs, cosmic-panel-bin/src/space_container/wrapper_space.rs, cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/data_device/data_source.rs, cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/pointer.rs, cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/seat.rs, cosmic-panel-bin/src/xdg_shell_wrapper/client/handlers/toplevel.rs, cosmic-panel-bin/src/xdg_shell_wrapper/client/state.rs, cosmic-panel-bin/src/xdg_shell_wrapper/mod.rs, cosmic-panel-bin/src/xdg_shell_wrapper/server/handlers/compositor.rs, cosmic-panel-bin/src/xdg_shell_wrapper/space/popup.rs, cosmic-panel-bin/src/xdg_shell_wrapper/space/space.rs, cosmic-panel-bin/src/xdg_shell_wrapper/space/toplevel.rs, cosmic-panel-bin/src/xdg_shell_wrapper/space/workspace.rs
A couple updates for changes in Smithay and cctk.
Also ran `cargo clippy --fix`, which helps to clean up some things.
=> Remove use of deprecated `from_loc_and_size`, and use just `ToplevelInfo` instead of tuple

cosmic-panel-config/src/panel_config.rs
This commit adds a new panel size to the PanelSize enum that allows users to specify an arbitrary size for the panel. Since there are a few different calculated values for each hardcoded panel size (XS, S, M, L, XL), I came up with some math to decide the sizes of applet icons and padding based on a rough average of each of the panel sizes, to hopefully capture the best size for everything with a custom panel size.
For a custom panel size of n:
get_dimensions returns 8 + gap..2n + 1 + gap
get_applet_icon_size returns n/2 for symbolic icons, 7n/10 for regular icons get_applet_padding returns n/4 for symbolic icons, 3n/20 for regular icons get_applet_icon_size_with_padding returns n for symbolic and regular icons
This results in a relatively balanced applet size and padding for any custom …
=> Add "Custom" panel size, with an arbitrary value for the size

cosmic-panel-bin/src/main.rs
Fixes issue where the notifications applet doesn't start properly at startup due to a timeout when connecting to the daemon:
```sh
❯ journalctl -b0 /usr/bin/cosmic-panel
Jun 13 18:38:15 zuka cosmic-panel[3295]: Failed to connect to the notifications daemon Err(Elapsed(()))
Jun 13 18:38:15 zuka cosmic-panel[3295]: Failed to connect to the notifications daemon Ok(Err(File exists (os error 17)))
Jun 13 18:38:15 zuka cosmic-panel[3295]: Can't start notifications applet without a connection
[...]
```
I've noticed that this issue affects both my 7 year old laptop and my 1/2 year old desktop PC, and only happens in the first login after boot, so I think it's a race condition with the daemon, but also not related to hardware speed.
=> fix: increase timeout for notifications proxy

flake.lock, flake.nix
This simplified flake is enough to compile & run a development version of cosmic-panel.
Rust's toolkit is not included as it's expected to use the system's rustup toolkit.
=> fix(nix): Reworked flake to work with current setup

cosmic-panel-bin/src/space/panel_space.rs, cosmic-panel-config/src/container_config.rs, cosmic-panel-config/src/panel_config.rs
Using COSMIC panel on a small screen laptop I have auto-hide enabled to maximize my screen real estate and using a "nub" pointer (or even a track pad) I often overshoot the top of the screen and cause the panel to un-hide unintentionally.
This feature just adds some delay or resistance before the panel un-hides, which works a lot better for this use case since I can overshoot and correct the position of the pointer without having to wait for the panel to hide in order to use the controls at the top of the window.
Mostly just looking for feedback/guidance on this, if there's appetite to get this merged I am happy to shepherd the change and get it into a state where it can be merged.
Corresponding PR for cosmic-settings: https://github.com/pop-os/cosmic-settings/pull/1400.
=> delay for un-hide / show of panel with autohide

cosmic-panel-bin/src/space/panel_space.rs
this tries to force tiled windows to rearrange. fixes https://github.com/pop-os/cosmic-settings/issues/1282
=> fix: briefly apply +-1 pixel when autohide changed
